### ISSUE TITLE
POST status 302 Found

### ISSUE THREAD

**Issue by daituzhang** [roundhouse/FormBuilder-Craft-CMS#20]
I try to do the post request from js
```
     $('form').submit(function(e) {
           var formData = $(this).serialize();
          $.post('formBuilder/entries/saveFormEntry', formData, function(response) {
            e.preventDefault();
             if (response.success) {
               console.log("success");
             } else {
               console.log("fail"); 
             }
          });
      }); 
```
but somehow I can not get the success response even the form submission, notification, entry saving are all working.From Browser inspect element net work, the status of the post request is 302 found, and no response back. Is there anyway I can get response back from post request? Thank you!

**Comment by owldesign** [comment]
The post url is wrong, it needs to be `admin/actions/formBuilder/entries/saveFormEntry`. But this won't work anyways because this plugin doesn't include ajax post submissions at the moment. 

I am currently rewriting this plugin, the new version will include ajax submissions. I'm planing on releasing the new version in a week...maybe sooner if I finish.

**Comment by daituzhang** [comment]
Thank you very much! Wait for your new version!
