### ISSUE TITLE
Hidden fields with variable values

### ISSUE THREAD

**Issue by disco666** [roundhouse/FormBuilder-Craft-CMS#43]
Hey there, it would be great to add hidden fields to the fieldtypes and optionally fill these with values from the current entry or any other dynamic values which are available in a template.

**Comment by owldesign** [comment]
I can add a new fieldtype `hidden field` to the list. Can you give me an example of what type of values you might want to put into a hidden field? Trying to understand what you are thinking.

**Comment by disco666** [comment]
Something like 
`<input type hidden name="title" value="{{ entry.title }}">`

**Comment by owldesign** [comment]
I can't seem to be able to pass twig template code into the values, they get rendered as `{{ entry.title }}` instead of actual entry title. Plus I'm using form macros to render input fields, and all these fields do not have access to `entry` variable. I feel there will need to be much work to get this working that might not be necessary because you can just simply add `<input type hidden name="title" value="{{ entry.title }}">` or any other hidden field to your template where the form is.. Just drop them bellow the rest of the hidden fields.

![see screenshot ](https://cloud.githubusercontent.com/assets/438764/9966474/fe57a672-5df1-11e5-940f-cf85d0838125.png)

I'll add a hidden fieldtype thought, but you'll have to manually pass a value. I will take a look at this further when I'll be rewriting formbuilder for Craft 3.

**Comment by disco666** [comment]
Alright, thanks for your reply. Everything is fine if manually added fields in the template are being saved automatically without having a defined field in the plugin. I thought this must be the case.
