### ISSUE TITLE
Linking to uploaded files

### ISSUE THREAD

**Issue by fduarte** [roundhouse/FormBuilder-Craft-CMS#54]
I see that the uploaded files end up in /craft/storage/formbuilder, as specified in the Asset Source (following the instructions in the Readme under File Uploads). However, it would be nice to be able to link to the uploaded files from FormBuilder > Entries, maybe by making the uploaded file name a hyperlink.

Could you explain how I'd go about that? Thanks!

**Comment by fduarte** [comment]
Also, the uploaded files appear in the Assets > Uploads... Except the link to the uploaded file doesn't work (clicking the checkbox next to the file and selecting 'view asset')

**Comment by owldesign** [comment]
I'd suggest you use the new FormBuilder 2 https://github.com/roundhouse/FormBuilder-2-Craft-CMS
It has better upload/assets controls.

Storage folder is protected so all the files that get put into it cannot be directly accessed through a link. You'd have to manually pull the files from ftp. I'd need to rebuild a lot to get this fixed. Which is why using the new plugin will be best because all of that is fixed there.

I'll be stopping support for this old version of plugin.

**Comment by fduarte** [comment]
Yeah that sounds good; however, if you upload a profile picture, you'll see it will go into craft/storage/userphotos, which is then accessible on the profile page with: 

/admin/resources/userphotos/<user_name>/100/picture_name.png

So there must be a way to access those form builder files, but this doesn't work:
/admin/resources/formbuilder/file_name.txt

**Comment by owldesign** [comment]
Craft probably has something built in that allows you to read files within that folder, I just know I wasn't able to figure it out :(

**Comment by fduarte** [comment]
It's all good, thanks for the help! :)
