### ISSUE TITLE
Don't get JSON-response when submitting with AJAX

### ISSUE THREAD

**Issue by KnutSv** [roundhouse/FormBuilder-Craft-CMS#7]
Tried submitting with AJAX but the response is HTML not JSON. Is it possible to return JSON with `success: true/false` and a success/error-message?

**Comment by krazyjakee** [comment]
I may be wrong, but I don't believe this is possible because this plugin utilises the templates and functionality that exist in the craft backend. If that functionality doesn't exist in crafts back-end then it won't exist in the front.

The alternative is to create your own templates from scratch using the field object and use twig to render the json `{{ results | json_encode() | raw }}`

**Comment by owldesign** [comment]
The next push I will utilize ajax for all form submissions, stay tuned.

**Comment by owldesign** [comment]
Form submission via Ajax is now available. Update your plugin please.
